apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: my-daemonset
  namespace: pooja
  labels: 
    app: java 
spec: 
selector:
  app: java
  matchLabels:
    name: my-daemonset
  template:
    metadata: 
         name: my-daemonset   
         labels: 
           app: java 
  
