apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
  namespace: pooja
  labels:
    type: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: deploy
  template:
    metadata:
      labels:
        type: deploy
    spec:
     containers:
     - name:  hr-web-app
       image: kodekloud/webapp-color
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hr-web-app-service
  namespace: pooja
spec:
  type: NodePort
  selector:
    type: deploy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30086








